use produto;

DELIMITER //
	DROP TRIGGER IF EXISTS TR_Cadastro_ProdutoSaldoAtualiza; //
	CREATE TRIGGER TR_Cadastro_ProdutoSaldoAtualiza AFTER INSERT ON TBPRODUTOMOVIMENTO
	FOR EACH ROW 
		BEGIN        
			IF NEW.CDSTIPOMOVIMENTO = 'E' THEN
				UPDATE 
						TBPRODUTO 
				SET		TBPRODUTO.NQTPRODUTOSALDO	=	TBPRODUTO.NQTPRODUTOSALDO + NEW.NQTPRODUTOMOVIMENTO
                WHERE	TBPRODUTO.NCDPRODUTO 		=	NEW.NCDPRODUTO;
            END IF;
		 
			IF NEW.CDSTIPOMOVIMENTO = 'S' OR NEW.CDSTIPOMOVIMENTO = 'C' THEN
				UPDATE 
						TBPRODUTO 
				SET		TBPRODUTO.NQTPRODUTOSALDO	=	TBPRODUTO.NQTPRODUTOSALDO - NEW.NQTPRODUTOMOVIMENTO
                WHERE	TBPRODUTO.NCDPRODUTO 		=	NEW.NCDPRODUTO;
            END IF;
         
		END//
DELIMITER ;