-- ==========================================================================================
/*
	Sistema:  		Controle de Produtos
	Versão:			1.0
    Data:			29/08/2015
    Banco de Dados:	Produto
    Descrição:		Criação da base e tabelas do sistema.
*/
-- ==========================================================================================

DROP DATABASE IF EXISTS Produto;
CREATE DATABASE Produto;
USE Produto;

CREATE TABLE TBPRODUTO(
	NCDPRODUTO 			INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CDSPRODUTO 			VARCHAR(100),
    NQTPRODUTOSALDO	 	INTEGER DEFAULT 0,
    BIDATIVO 			BOOLEAN 
);

CREATE TABLE TBPRODUTOMOVIMENTO(
	NCDPRODUTOMOVIMENTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NCDPRODUTO			INT NOT NULL,
    NQTPRODUTOMOVIMENTO	FLOAT,
	CDSOBSERVACAO		VARCHAR(300),
    CDSTIPOMOVIMENTO	CHAR(1),
    DTMOVIMENTO			DATETIME,
	FOREIGN KEY (NCDPRODUTO) REFERENCES TBPRODUTO (NCDPRODUTO)
);

use produto;
CREATE TABLE TBMENU
(
	NCDMENU				 INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CNMMENU 			 VARCHAR(100),
	CDSENDERECO 		 VARCHAR(200),
	CDSURL 				 VARCHAR(200),
	BIDIMAGEM 			 BOOLEAN,
	BIDITEMSEGURANCA 	 BOOLEAN,
	BIDINDICADORABERTURA BOOLEAN,
	ORDEM 				 INT,
	NCDMENU_PAI 		 INT NULL,
    FOREIGN KEY (NCDMENU_PAI) REFERENCES TBMENU(NCDMENU)
);