-- ==========================================================================================
/*
	Sistema:  		Controle de Produtos
	Versão:			1.0
    Data:			29/08/2015
    Banco de Dados:	Produto
    Descrição:		Criação da base e tabelas do sistema.
*/
-- ==========================================================================================

DROP DATABASE IF EXISTS Produto;
CREATE DATABASE Produto;
USE Produto;

-- ==========================================================================================
/*
	SISTEMA DE CONTROLE DE ESTOQUE
*/
-- ==========================================================================================

CREATE TABLE TBPRODUTO
(
	NCDPRODUTO 							INT 			NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CDSPRODUTO 							VARCHAR(100)		NULL,	
    NQTPRODUTOSALDO	 					INTEGER 		NOT	NULL DEFAULT 0,
    BIDATIVO 							BOOLEAN 		NOT NULL DEFAULT 1
);

CREATE TABLE TBPRODUTOMOVIMENTO
(
	NCDPRODUTOMOVIMENTO 	 			INT 			NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NCDPRODUTO				 			INT 			NOT NULL,
    NQTPRODUTOMOVIMENTO		 			FLOAT				NULL,
	CDSOBSERVACAO			 			VARCHAR(300)		NULL,
    CDSTIPOMOVIMENTO		 			CHAR(1)				NULL,
    DTMOVIMENTO				 			DATETIME			NULL,
	FOREIGN KEY (NCDPRODUTO) 			REFERENCES TBPRODUTO (NCDPRODUTO)
);

-- ==========================================================================================
/*
	SISTEMA DE SEGURANÇA
*/
-- ==========================================================================================
CREATE TABLE TBFUNCIONALIDADE
(
	NCDFUNCIONALIDADE		 			INT 			NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CDSFUNCIONALIDADE		 			VARCHAR(200)		NULL,
    CNMFUNCIONALIDADE		 			VARCHAR(200)		NULL,
    BIDATIVO				 			BOOLEAN 		NOT NULL DEFAULT 1
);

CREATE TABLE TBSUBFUNCIONALIDADE(
	NCDSUBFUNCIONALIDADE	 			INT 			NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NCDFUNCIONALIDADE		 			INT NULL,
    CDSSUBFUNCIONALIDADE	 			VARCHAR(200),    
    FOREIGN KEY(NCDFUNCIONALIDADE) 		REFERENCES TBFUNCIONALIDADE(NCDFUNCIONALIDADE)
);


CREATE TABLE TBUSUARIO(
	NCDUSUARIO				 			INT 			NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CDSUSUARIO				 			VARCHAR(200)		NULL,
    CNMUSUARIO				 			VARCHAR(200)		NULL,
    CDSSENHA							VARCHAR(128)		NULL,
    BIDATIVO				 			BOOLEAN 		NOT NULL DEFAULT 1
);

CREATE TABLE TBPERMISSAOACESSO(
	NCDPERMISSAOACESSO					INT 			NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NCDFUNCIONALIDADE					INT				NOT NULL,
    NCDSUBFUNCIONALIDADE				INT					NULL,
    NCDUSUARIO							INT				NOT NULL,	
    DDTINCLUSAO							DATETIME		NOT NULL DEFAULT NOW(),
    FOREIGN KEY(NCDFUNCIONALIDADE) 		REFERENCES TBFUNCIONALIDADE(NCDFUNCIONALIDADE),
    FOREIGN KEY(NCDSUBFUNCIONALIDADE) 	REFERENCES TBSUBFUNCIONALIDADE(NCDSUBFUNCIONALIDADE),
    FOREIGN KEY(NCDUSUARIO) 			REFERENCES TBUSUARIO(NCDUSUARIO)
);


INSERT INTO TBFUNCIONALIDADE (CDSFUNCIONALIDADE, CNMFUNCIONALIDADE, BIDATIVO) VALUES('(Cadastro)(Produto)(Cadastro de Produto)','frm_Cadastro_Produto_Carrega.aspx', 1);
INSERT INTO TBFUNCIONALIDADE (CDSFUNCIONALIDADE, CNMFUNCIONALIDADE, BIDATIVO) VALUES('(Procedimento)(Produto)(Movimento de Produto)','frm_Movimento_Produto_Carrega.aspx', 1);
INSERT INTO TBFUNCIONALIDADE (CDSFUNCIONALIDADE, CNMFUNCIONALIDADE, BIDATIVO) VALUES('(Segurança)(Usuário)(Cadastro de Usuário)','frm_SG_Usuario_Carrega.aspx', 1);
INSERT INTO TBFUNCIONALIDADE (CDSFUNCIONALIDADE, CNMFUNCIONALIDADE, BIDATIVO) VALUES('(Segurança)(Usuário)(Permissões por Usuário)','frm_SG_UsuarioPermissao_IncluiExclui.aspx', 1);
/*INSERT INTO TBSUBFUNCIONALIDADE(NCDFUNCIONALIDADE, CDSSUBFUNCIONALIDADE) VALUES(1, '(Inclusão)');
INSERT INTO TBSUBFUNCIONALIDADE(NCDFUNCIONALIDADE, CDSSUBFUNCIONALIDADE) VALUES(1, '(Alteração)');*/
INSERT INTO TBUSUARIO(CDSUSUARIO, CNMUSUARIO, CDSSENHA, BIDATIVO) VALUES('Administrador', 'admin', 'D61D004C03457BAC7B90C1E8D4F51113BE162346B27AF5307CAFFE21EF88597FF15AB1569E07155302FF7B0AF29F7F0431531004568DA3849A5708176815A70F', 1);